name: Build OpenWRT package (test)

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt version to test'
        required: true
        default: '24.10'
        type: choice
        options:
        - '24.10'
        - '25.12'
      verbose:
        description: 'Verbose build output'
        required: false
        default: false
        type: boolean

jobs:
  build-test:
    name: Build Test - OpenWrt ${{ matrix.openwrt_version }}
    strategy:
      matrix:
        include:
          - openwrt_version: '24.10'
            openwrt_build_version: '24.10.5'
            arch: 'x86_64'
          - openwrt_version: '25.12'
            openwrt_build_version: '25.12.0'
            arch: 'x86_64'
      fail-fast: false

    permissions: {}
    uses: Zerogiven/gh-openwrt-package-build-workflows/.github/workflows/reusable-build.yml@prometheus-node-exporter-lua-patch
    with:
      package_name: 'luci-app-podman'
      sdk_packages: 'luci-app-podman'
      artifacts_patterns: |
        luci-app-podman*.ipk
        luci-i18n-podman-*.ipk
        luci-app-podman*.apk
        luci-i18n-podman-*.apk
      openwrt_version: ${{ matrix.openwrt_version }}
      openwrt_build_version: ${{ matrix.openwrt_build_version }}
      arch: ${{ matrix.arch }}
      selected_version: ${{ github.event.inputs.openwrt_version }}
      free_disk_space: true
      create_swap: false
      verbose: ${{ github.event.inputs.verbose == 'true' }}
